### ISSUE TITLE
`cursor: pointer`  в секции "Реализованные проекты"

### ISSUE THREAD

**Issue by foxhable** [aaccent/real-time_layout#2]
На `div`'ах с миниатюрами фотографий в секции "Реализованные проекты" сделай `cursor: pointer`

<details><summary>Скрин</summary>

![image](https://github.com/user-attachments/assets/bc8d924c-ec29-4935-b5b9-291c68b4ec95)
</details>

**Comment by RamizAshurov** [comment]
Исправил
