### ISSUE TITLE
Стрелка у "Читать полностью"

### ISSUE THREAD

**Issue by foxhable** [aaccent/real-time_layout#3]
В секции "Коммерческое проектирование" у кнопки "Читать полностью" в макете есть стрелка справ от текста
<details><summary>Скрин</summary>

![image](https://github.com/user-attachments/assets/92980e8e-2f20-4b34-8160-658be0db9025)
</details>

**Comment by RamizAshurov** [comment]
![image](https://github.com/user-attachments/assets/9266ec97-1e7b-4cf0-b30b-aaa5174e9e2b)
Стрелка на месте на всех страницах
