### ISSUE TITLE
Мобильная карта

### ISSUE THREAD

**Issue by foxhable** [aaccent/real-time_layout#5]
1. Есть ли возможность сместить её вверх. Иначе плашка перекрывает надпись о том, что нужно пользовать двумя пальцами
<details><summary>Скрин</summary>

![image](https://github.com/user-attachments/assets/b2fdde8d-968a-4809-a3a2-b31c8f6fb3ff)
</details> 

2. Нужно сместить изначальные рамки карты, чтобы метка была выше, иначе перекрывается плашкой
<details><summary>Скрин</summary>

![image](https://github.com/user-attachments/assets/2b4c7234-d7e9-405e-a599-d62685b20942)
</details>

**Comment by RamizAshurov** [comment]
1. исправил
2. исправил
