### ISSUE TITLE
Кнопка "Рассчитать стоимость"

### ISSUE THREAD

**Issue by foxhable** [aaccent/real-time_layout#6]
На странице Услуги и Подуслуги кнопка "Рассчитать стоимость" должна вызывать попап звонка при нажатии пользователем

<details><summary>Скрин</summary>

![image](https://github.com/user-attachments/assets/3104a4f7-0b38-4e5c-a16b-2e456c500844)
</details>

**Comment by RamizAshurov** [comment]
Сделал
